services:
  - type: web
    name: study-analyzer
    env: docker
    region: oregon
    plan: free
    rootDir: Smart Study Analyzer
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login.jsp
    envVars:
      - key: DB_HOST
        value: mysql-5b350a9-sanjeys007-5567.l.aivencloud.com
      - key: DB_PORT
        value: 10532
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
